baseURL = 'https://danielkiss.online/'
languageCode = 'hu-hu'
title = 'Kiss Dániel'

[menu]

  [[menu.main]]
    identifier = "jegyzetek"
    name = "jegyzetek"
    url = "/jegyzetek"
    weight = 10

  [[menu.main]]
    identifier = "teszt"
    name = "teszt"
    url = "teszt"
    weight = 20
